### ISSUE TITLE
yarn install 之后 ，run dev 出现了这个问题。。

### ISSUE THREAD

**Issue by blockmood** [JasonBoy/koa-web-kit#39]
```
(node:58220) UnhandledPromiseRejectionWarning: TypeError: res.getHeader is not a function
    at processRequest (/Users/blockmood/Desktop/pc/node_modules/webpack-dev-middleware/lib/middleware.js:82:18)
    at ready (/Users/blockmood/Desktop/pc/node_modules/webpack-dev-middleware/lib/util.js:51:12)
    at handleRequest (/Users/blockmood/Desktop/pc/node_modules/webpack-dev-middleware/lib/util.js:167:5)
    at Promise (/Users/blockmood/Desktop/pc/node_modules/webpack-dev-middleware/lib/middleware.js:44:7)
    at new Promise (<anonymous>)
    at middleware (/Users/blockmood/Desktop/pc/node_modules/webpack-dev-middleware/lib/middleware.js:43:12)
    at Promise (/Users/blockmood/Desktop/pc/node_modules/koa-webpack/lib/middleware.js:28:9)
    at new Promise (<anonymous>)
    at /Users/blockmood/Desktop/pc/node_modules/koa-webpack/lib/middleware.js:27:20
    at dispatch (/Users/blockmood/Desktop/pc/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at createGenerator (/Users/blockmood/Desktop/pc/node_modules/koa-convert/index.js:24:16)
    at createGenerator.next (<anonymous>)
    at Object.<anonymous> (/Users/blockmood/Desktop/pc/node_modules/koa-history-api-fallback/lib/index.js:104:5)
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/blockmood/Desktop/pc/node_modules/co/index.js:65:19)
    at /Users/blockmood/Desktop/pc/node_modules/co/index.js:54:5
(node:58220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by blockmood** [comment]
我降低了koa-webpack的版本表示也不行。

**Comment by JasonBoy** [comment]
没遇到过，你用的是当前项目的哪个版本?`koa-history-api-fallback`是哪个版本

**Comment by blockmood** [comment]
@JasonBoy 
```
 "koa-history-api-fallback": "0.1.3",
```

**Comment by JasonBoy** [comment]
系统基本信息是什么，你使用的当前项目koa-web-kit截止到哪个版本？

**Comment by blockmood** [comment]
@JasonBoy 

```
{
  "name": "koa-web-kit",
  "version": "2.8.2",
  "description": "A modern, production-ready, and full-stack node web framework",
  "main": "index.js",
  "scripts": {
    "dev": "cross-env ENABLE_HMR=1 ENABLE_SSR=0 STATIC_PREFIX='' node server.js",
    "dev:ssr": "cross-env NODE_ENV='development' ENABLE_HMR=0 CSS_MODULES=0 ENABLE_SSR=1 npm-run-all -p watch watch:ssr start",
    "dev:watch": "cross-env ENABLE_HMR=0 ENABLE_SSR=0 npm-run-all -p watch start",
    "start": "nodemon --trace-warnings server.js",
    "deploy": "./deploy.sh",
    "deploy:beta": "cross-env NODE_ENV='development' NODE_CONFIG_PATH=config.default.dev.js npm run deploy -- 1 0 0 2",
    "deploy:release": "cross-env NODE_ENV='production' NODE_CONFIG_PATH=config.default.prod.js npm run deploy -- 1 0 0 2",
    "build:dev": "webpack --progress --hide-modules --config config/webpack.config.dev.js",
    "ssg": "cross-env STATIC_PREFIX='' APP_PREFIX='' PREFIX_TRAILING_SLASH='' npm run build",
    "watch": "webpack --watch --progress --hide-modules --config config/webpack.config.dev.js",
    "node": "webpack --progress --config config/webpack.config.node.js",
    "watch:ssr": "npm run ssr -- --watch",
    "ssr": "webpack --progress --config config/webpack.config.ssr.js",
    "build": "cross-env NODE_ENV=production VERSION=1 webpack -p --progress --hide-modules --config config/webpack.config.prod.js ",
    "report": "cross-env NODE_ENV=production BUNDLE_ANALYZER=true webpack -p --progress --hide-modules --config config/webpack.config.prod.js",
    "test": "npm run jest:node && npm run jest:client",
    "jest:node": "jest --config=jest.config.node.js --forceExit",
    "jest:client": "jest --config=jest.config.client.js",
    "build:cdn": "cross-env NODE_ENV=production VERSION=1 ENABLE_SSR=0 webpack -p --progress --hide-modules --config config/webpack.config.prod-cdn.js",
    "build:cdn_dev": "cross-env NODE_ENV=development VERSION=1 ENABLE_SSR=0 webpack -p --progress --hide-modules --config config/webpack.config.dev.js"
  },
  "engines": {
    "node": ">= 8.3"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "linters": {
      "**/*.{js,jsx,json,scss,html}": [
        "prettier --write",
        "git add"
      ]
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/JasonBoy/koa-web-kit.git"
  },
  "keywords": [
    "koa",
    "es6",
    "webpack",
    "react",
    "bootstrap",
    "fullstack",
    "framework"
  ],
  "author": "jasonlikenfs@gmail.com",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/JasonBoy/koa-web-kit/issues"
  },
  "homepage": "https://github.com/JasonBoy/koa-web-kit#readme",
  "readme": "README.md",
  "dependencies": {
    "@loadable/component": "^5.6.0",
    "@loadable/server": "^5.6.0",
    "antd": "^3.13.5",
    "axios": "^0.18.0",
    "babel-polyfill": "6.26.0",
    "bootstrap": "4.3.1",
    "chalk": "2.4.2",
    "classnames": "2.2.6",
    "crypto-js": "^3.1.9-1",
    "date-fns": "1.30.1",
    "echarts": "^4.1.0",
    "got": "9.6.0",
    "history": "4.7.2",
    "html-minifier": "3.5.21",
    "into-stream": "4.0.0",
    "isomorphic-fetch": "^2.2.1",
    "js-cookie": "^2.2.0",
    "js-md5": "^0.7.3",
    "koa": "2.7.0",
    "koa-body": "4.0.8",
    "koa-compress": "3.0.0",
    "koa-convert": "1.2.0",
    "koa-favicon": "2.0.1",
    "koa-helmet": "4.0.0",
    "koa-morgan": "1.0.1",
    "koa-mount": "4.0.0",
    "koa-pino-logger": "2.1.3",
    "koa-router": "7.4.0",
    "koa-session": "5.10.1",
    "koa-static": "5.0.0",
    "koa-static-cache": "^5.1.2",
    "lodash.isempty": "4.4.0",
    "make-dir": "2.0.0",
    "memory-cache": "^0.2.0",
    "pino": "5.11.1",
    "pino-pretty": "2.5.0",
    "pm2": "^3.3.1",
    "prop-types": "15.7.2",
    "rc-form": "^2.2.3",
    "react": "16.8.1",
    "react-addons-css-transition-group": "^15.6.2",
    "react-dom": "16.8.1",
    "react-redux": "^6.0.1",
    "react-router-dom": "4.3.1",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "slugify": "1.3.4",
    "swiper": "^4.4.6",
    "tunnel": "0.0.6",
    "whatwg-fetch": "3.0.0"
  },
  "devDependencies": {
    "@babel/cli": "7.2.3",
    "@babel/core": "7.2.2",
    "@babel/helper-module-imports": "7.0.0",
    "@babel/plugin-proposal-class-properties": "7.3.0",
    "@babel/plugin-proposal-object-rest-spread": "7.3.2",
    "@babel/plugin-syntax-dynamic-import": "7.2.0",
    "@babel/plugin-transform-modules-commonjs": "7.2.0",
    "@babel/plugin-transform-react-jsx-source": "7.2.0",
    "@babel/plugin-transform-runtime": "7.2.0",
    "@babel/preset-env": "7.3.1",
    "@babel/preset-react": "7.0.0",
    "@babel/runtime": "7.3.1",
    "@loadable/babel-plugin": "5.6.0",
    "@loadable/webpack-plugin": "5.5.0",
    "autoprefixer": "9.4.7",
    "babel-loader": "8.0.5",
    "babel-minify-webpack-plugin": "0.3.1",
    "babel-plugin-dynamic-import-node": "2.2.0",
    "babel-plugin-import": "^1.12.0",
    "cheerio": "1.0.0-rc.2",
    "clean-webpack-plugin": "1.0.1",
    "copy-webpack-plugin": "4.6.0",
    "cross-env": "^5.2.0",
    "css-loader": "2.1.0",
    "error-overlay-webpack-plugin": "0.1.6",
    "file-loader": "3.0.1",
    "get-port": "4.1.0",
    "html-loader": "0.5.5",
    "html-webpack-plugin": "3.2.0",
    "husky": "1.3.1",
    "ignore-loader": "0.1.2",
    "jest": "24.1.0",
    "jquery": "3.3.1",
    "json-server": "0.14.2",
    "koa-history-api-fallback": "0.1.3",
    "koa-webpack": "5.2.1",
    "lint-staged": "8.1.3",
    "mini-css-extract-plugin": "0.5.0",
    "nock": "10.0.6",
    "node-sass": "4.11.0",
    "nodemon": "1.18.10",
    "npm-run-all": "4.1.5",
    "popper.js": "1.14.7",
    "postcss-loader": "3.0.0",
    "preload-webpack-plugin": "3.0.0-beta.2",
    "prettier": "1.16.4",
    "sass-loader": "7.1.0",
    "shelljs": "0.8.3",
    "style-loader": "0.23.1",
    "supertest": "3.4.2",
    "terser-webpack-plugin": "1.2.2",
    "url-loader": "1.1.2",
    "webpack": "4.28.4",
    "webpack-bundle-analyzer": "3.0.4",
    "webpack-cli": "3.2.3",
    "webpack-manifest-plugin": "2.0.4",
    "webpack-merge": "4.2.1",
    "webpack-node-externals": "1.7.2"
  },
  "browserslist": [
    "> 1%",
    "ie >= 9",
    "not op_mini all"
  ],
  "nodemonConfig": {
    "watch": [
      "api/",
      "config/",
      "build/node",
      "routes/",
      "utils/",
      "services/",
      "app-config.js",
      "server.js"
    ]
  }
}

```

**Comment by blockmood** [comment]
我之前环境是没问题的，也不知道怎么就run dev 跑不起来了，

**Comment by blockmood** [comment]
因为要兼容ie9 我加入了babel-polyfill ， 
yarn install 了之后 , run dev 跑不起来，但是build的文件 ie9 能够正常访问，  
npm install 之后 , run dev能跑起来，但是build的ie9 不支持，很尴尬。
